services:
  timekeeper:
    build: .
    network_mode: host
    extra_hosts:
        - "isc-coordinator2.lan:192.168.88.226"
        - "isc-coordinator1.lan:192.168.88.250"
    privileged: true
    tty: true
    volumes:
      - /var/run/dbus:/var/run/dbus
    env_file:
      - .env
    restart: unless-stopped
