services:
  ur_agent:
    build: .
    container_name: ur-agent
    profiles: ["ur"]
    extra_hosts:
      - "isc-coordinator.lan:192.168.88.250"
      - "isc-coordinator2.lan:192.168.88.226"
    env_file:
      - .env
    volumes:
      - ./ur_robot:/app/ur_robot
      - ./urbasic:/app/urbasic
    privileged: true