#!/bin/bash
# Deployment script for CameraAgent
LOGFILE=deploy.log
echo "$(date) - Deployment started" >> $LOGFILE
echo "$(date) - Deployment started"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_PATH="${SCRIPT_DIR}"

# Load .env file (local config for deployment)
ENV_FILE="${LOCAL_PATH}/.env"
if [ -f $ENV_FILE ]; then
    source $ENV_FILE
else
    echo "$ENV_FILE file not found" >> $LOGFILE
    echo "$ENV_FILE file not found"
    exit 1
fi

# Select XMPP coordinator (server) the bot's agents will connect to
read -rp "Select XMPP coordinator to connect (1-2): " coordinator
if [[ ! $coordinator =~ ^[1-2]$ ]]; then
    echo "Invalid XMPP coordinator choice ${coordinator}. Exiting." >> $LOGFILE
    echo "Invalid XMPP coordinator choice ${coordinator}. Exiting."
    exit 1
fi

REMOTE_HOST_VAR="REMOTE_HOST_${coordinator}"
XMPP_DOMAIN_VAR="XMPP_DOMAIN_${coordinator}"

REMOTE_HOST="${!REMOTE_HOST_VAR}"
XMPP_DOMAIN="${!XMPP_DOMAIN_VAR}"

# Select UR Robot IP
read -rp "Select UR Robot IP (1:${UR_ROBOT_IP_1} - 2:${UR_ROBOT_IP_2}): " coordinator
if [[ ! $coordinator =~ ^[1-2]$ ]]; then
    echo "Invalid UR Robot IP choice ${coordinator}. Exiting." >> $LOGFILE
    echo "Invalid UR Robot IP choice ${coordinator}. Exiting."
    exit 1
fi

UR_ROBOT_IP_VAR="UR_ROBOT_IP_${coordinator}"
UR_ROBOT_IP="${!UR_ROBOT_IP_VAR}"

# Default values
SSH_PORT=${SSH_PORT:-22}
RSYNC_OPTS=${RSYNC_OPTS:--avz --delete}

# Generate .env file for the selected bot
TEMPLATE="${LOCAL_PATH}/.env.template"
OUTPUT="${LOCAL_PATH}/.env"

cp "$TEMPLATE" "$OUTPUT"

# Add header comment
tmpfile=$(mktemp)
{
    echo "# ---------------------------------------------------------"
    echo "# This file was generated automatically by deploy_spadecontroller.sh"
    echo "# Do NOT edit this file manually."
    echo "# If you need to change values, edit .env.template or .env"
    echo "# ---------------------------------------------------------"
    echo
    echo "# Generated for bot $bot_choice connecting to XMPP coordinator $coordinator"
    echo
    cat "$OUTPUT"
} > "$tmpfile"

mv "$tmpfile" "$OUTPUT"

sed -i "s|{{REMOTE_HOST}}|$REMOTE_HOST|g" "$OUTPUT"
sed -i "s|{{XMPP_DOMAIN}}|$XMPP_DOMAIN|g" "$OUTPUT"
sed -i "s|{{XMPP_USERNAME}}|$XMPP_USERNAME|g" "$OUTPUT"
sed -i "s|{{UR_ROBOT_IP}}|$UR_ROBOT_IP|g" "$OUTPUT"

echo "Deploying folder to ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}" >> $LOGFILE
echo "Using rsync options: ${RSYNC_OPTS}" >> $LOGFILE
echo "XMPP base JID will be: ${XMPP_USERNAME}@${XMPP_DOMAIN}" >> $LOGFILE
echo "UR Robot IP will be: ${UR_ROBOT_IP}" >> $LOGFILE
echo "Deploying folder to ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"
echo "Using rsync options: ${RSYNC_OPTS}"
echo "XMPP base JID will be: ${XMPP_USERNAME}@${XMPP_DOMAIN}"
echo "UR Robot IP will be: ${UR_ROBOT_IP}"

# Confirm deployment
echo "Did you check the agents XMPP name?"
read -rp "Proceed with deployment? (y/n) " confirm
[[ "$confirm" != "y" ]] && exit 0

# Run rsync
rsync ${RSYNC_OPTS} -e "ssh -p ${SSH_PORT}" \
    "${LOCAL_PATH}/" \
    "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}/"

echo "Deployment complete." >> $LOGFILE
echo "Deployment complete."
